# Generated by Django 5.0.6 on 2024-06-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='description',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='nome',
        ),
    ]
